# Generated by Django 3.2.9 on 2021-11-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, default='fast', max_length=50, null=True, unique=True),
        ),
    ]
